name: new-pre-release

on:
    workflow_dispatch:
        inputs:
            tag_value:
                description: 'Tag value'
                required: true
                type: string

jobs:
    check-tag:
        runs-on: ubuntu-latest

        if: ${{ inputs.tag_value }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Check for Tag
              run: |
                  TAG="${{ inputs.tag_value }}"
                  if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
                    echo "Tag ${TAG} exists"
                  else
                    echo "Tag ${TAG} does not exist"
                  fi
