name: new-pre-release

on:
    workflow_dispatch:
        inputs:
            tag_value:
                description: 'Set TAG value. without "v"!'
                required: true
                type: string

jobs:
    create-rc:
        runs-on: ubuntu-latest

        if: ${{ inputs.tag_value }}
        steps:
            - name: Checkout branch dev
              uses: actions/checkout@v3
              with:
                  ref: dev

            - uses: actions/setup-node@v3

            - name: Create branch rc${{ inputs.tag_value }}
              shell: bash
              run: |
                  git checkout -b rc${{ inputs.tag_value }}
                  git push -u origin rc${{ inputs.tag_value }}

    set-tag:
        needs: create-rc
        runs-on: ubuntu-latest

        if: ${{ inputs.tag_value }}
        steps:
            # TODO: Remove the setUp git below since it will not be needed once token will be set
            - name: Configure Git with the GitHub Token
              run: |
                  git config --global user.email "sa_git_uicomponents@outsystems.com"
                  git config --global user.name "UiComponentsBot"
                  git config --global credential.helper store

            - name: Checkout branch dev
              uses: actions/checkout@v3
              with:
                  ref: rc${{ inputs.tag_value }}
                  fetch-depth: 0
                  # token: ${{ secrets.PAT }}

            - name: Set tag
              run: |
                  git tag -a ${{ inputs.tag_value }} -m "New v${{ inputs.tag_value }} tag."
                  git push origin --tags
