name: new-pre-release

on:
    workflow_dispatch:
        inputs:
            tag_value:
                description: 'Tag value'
                required: true
                type: string

jobs:
    print-tag:
        runs-on: ubuntu-latest
        if: ${{ inputs.tag_value }}
        steps:
            - name: Print the input tag value
              run: echo  The tag is ${{ inputs.tag_value }} at the branch ${{ github.ref_name }}
