name: new-pre-release

on:
    workflow_dispatch:
        inputs:
            tag_value:
                description: 'Tag value'
                required: true
                type: string

jobs:
    set-tag:
        runs-on: ubuntu-latest

        if: ${{ inputs.tag_value }}
        steps:
            # TODO: Remove the setUp git below since it will not be needed once token will be set
            - name: Configure Git with the GitHub Token
              run: |
                  git config --global user.email "sa_git_uicomponents@outsystems.com"
                  git config --global user.name "UiComponentsBot"
                  git config --global credential.helper store

            # - name: Checkout
            #   uses: actions/checkout@v3
            #   with:
            #       fetch-depth: 0
            #       token: ${{ secrets.PAT }}

            # - name: Set env
            #   run: echo "TAG_TO_CREATE=$(echo ${{ inputs.tag_value }})" >> $GITHUB_ENV

            - name: Set tag
              run: |
                  git tag -a ${{ inputs.tag_value }} -m "my version ${{ inputs.tag_value }}"
                  git push origin --tags
