name: new-pre-release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The type of version to release.'
                type: string
                required: true

jobs:
    create-rc:
        runs-on: ubuntu-latest

        if: ${{ inputs.version }}
        steps:
            - name: Checkout branch dev
              uses: actions/checkout@v3
              with:
                  ref: dev

            - uses: actions/setup-node@v3

            - name: Create branch rc${{ inputs.version }}
              shell: bash
              run: |
                  echo cenas_${{ inputs.BRANCH }}
                  git checkout -b rc${{ inputs.version }}
                  git push -u origin rc${{ inputs.version }}

    set-tag:
        needs: create-rc
        runs-on: ubuntu-latest

        if: ${{ inputs.version }}
        steps:
            # TODO: Remove the setUp git below since it will not be needed once token will be set
            - name: Configure Git with the GitHub Token
              run: |
                  git config --global user.email "sa_git_uicomponents@outsystems.com"
                  git config --global user.name "UiComponentsBot"
                  git config --global credential.helper store

            - name: Checkout branch dev
              uses: actions/checkout@v3
              with:
                  ref: rc${{ inputs.version }}
                  fetch-depth: 0
                  token: ${{ secrets.PAT }}

            - name: Set tag
              run: |
                  git tag v${{ inputs.version }} HEAD -m "Version ${{ inputs.version }} released"
                  git push origin --tags
