name: new-pre-release

on:
    workflow_dispatch:
        inputs:
            new-version:
                description: 'New version to be set.'
                type: string
                required: true
            release-date:
                description: 'Set the release date.'
                type: string
                required: true

jobs:
    create-rc:
        runs-on: ubuntu-latest

        if: ${{ github.event.inputs.new-version }}
        steps:
            - name: Checkout branch dev
              uses: actions/checkout@v3
              with:
                  ref: dev

            - uses: actions/setup-node@v3

            - name: Create branch rc${{ github.event.inputs.new-version }}
              shell: bash
              run: |
                  git checkout -b rc${{ github.event.inputs.new-version }}
                  git push -u origin rc${{ github.event.inputs.new-version }}

    set-tag:
        needs: create-rc
        runs-on: ubuntu-latest

        if: ${{ github.event.inputs.new-version }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch all commits and tags

            # TODO: Remove the setUp git below since it will not be needed once token will be set
            # - name: Configure Git with the GitHub Token
            #   run: |
            #       git config --global user.email "sa_git_uicomponents@outsystems.com"
            #       git config --global user.name "UiComponentsBot"
            #       git config --global credential.helper store

            - name: Checkout branch dev
              uses: actions/checkout@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  ref: rc${{ github.event.inputs.new-version }}
                  #   token: ${{ secrets.PAT }}

            - name: Set tag
              run: |
                  git tag v${{ github.event.inputs.new-version }} HEAD -m "Version ${{ github.event.inputs.new-version }} released"
                  git push origin --tags

    set-prerelease:
        needs: set-tag
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch all commits and tags

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ github.event.inputs.new-version }}
                  release_name: Release of version ${{ github.event.inputs.new-version }} (${{ github.event.inputs.release-date }})
                  body: |
                      Changes in this Release
                      - First Change
                      - Second Change
                  draft: false
                  prerelease: true
